mapslizle.exe --src D:\PCH\FPS\GR-0.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-1.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-2.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-3.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-4.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-5.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-6.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\GR-7.png --dst D:\PCH\FPS\00Floor\Tiles --name GR --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L1-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L1 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L2-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L2 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L3-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L3 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L4-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L4 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L5-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L5 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L6-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L6 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L7-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L7 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L8 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L9-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L9 --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-0.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-1.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-2.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-3.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-4.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-5.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-6.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\UB-7.png --dst D:\PCH\FPS\00Floor\Tiles --name UB --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-0.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-1.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-2.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-3.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-4.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-5.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-6.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\LB-7.png --dst D:\PCH\FPS\00Floor\Tiles --name LB --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L8A-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L8A --zoom 7 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-0.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 0 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-1.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 1 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-2.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 2 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-3.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 3 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-4.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 4 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-5.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 5 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-6.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 6 --sq 256 slice
mapslizle.exe --src D:\PCH\FPS\L10-7.png --dst D:\PCH\FPS\00Floor\Tiles --name L10 --zoom 7 --sq 256 slice
